server:
  port: 9001

spring:
  application:
    name: index12306-user${unique-name:}-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:12306_user;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register:
          name: user_register_cache_penetration_bloom_filter${unique-name:}
